caffeine:
  caches:
    - name: coffeeCache
      expiryDurationTimeUnit: SECONDS
      expiryDurationAmount: 60
    - name: coffeeCacheV2
      expiryDurationTimeUnit: MINUTES
      expiryDurationAmount: 1
