webclient:
  connectionTimeout: 2000
  readTimeout: 2000
  pool:
    maxConnections: 1000
    pendingAcquireMaxCount: 2000
    maxIdleTime: 50s
    maxLifeTime: 50s
    evictInBackground: 100s
    metricsEnabled: true

client:
  hello:
    baseUrl: http://127.0.0.1:9090
  world:
    baseUrl: http://127.0.0.1:9090
  hi:
    baseUrl: http://127.0.0.1:9090

logging:
  level:
    reactor:
      netty: debug

management.endpoints.web.exposure.include: "*"

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 2s
      cancelRunningFuture: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 1