spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://configserver:8071
#  config:
#    import: "configserver:"
#  cloud:
#    config:
#      uri: http://configserver:8071