version: '3.7'

services:
  configserver:
    image: ostack/configserver:0.0.1-SNAPSHOT
    ports:
       - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  licensingservice:
    image: ostack/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
    networks:
      - backend

networks:
  backend:
    driver: bridge