resilience4j.circuitbreaker:
  instances:
    review-service:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 4
      minimumNumberOfCalls: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
        - java.util.concurrent.TimeoutException
resilience4j.ratelimiter:
  instances:
    calculator-service:
      limitRefreshPeriod: 20s
      limitForPeriod: 5
      timeoutDuration: 5s # 요청이 초과되어도 17s에 들어온다면 타임아웃(17+5=22)되기 전에 20초가 되기 때문에 다음 윈도우에 들어가게 된다.

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

# 01. Aggregator Pattern
sec01.product.service: http://localhost:7070/sec01/product/
sec01.promotion.service: http://localhost:7070/sec01/promotion/
sec01.review.service: http://localhost:7070/sec01/review/
  
# 02. Scatter Gather Pattern
sec02.delta.service: http://localhost:7070/sec02/delta/
sec02.frontier.service: http://localhost:7070/sec02/frontier/
sec02.jetblue.service: http://localhost:7070/sec02/jetblue/

# 03. Orchestration Pattern (SAGA - for parallel workflow)
sec03.product.service: http://localhost:7070/sec03/product/
sec03.user.service: http://localhost:7070/sec03/user/
sec03.inventory.service: http://localhost:7070/sec03/inventory/
sec03.shipping.service: http://localhost:7070/sec03/shipping/

# 04. Orchestrator Pattern (for sequential workflow)
sec04.product.service: http://localhost:7070/sec04/product/
sec04.user.service: http://localhost:7070/sec04/user/
sec04.inventory.service: http://localhost:7070/sec04/inventory/
sec04.shipping.service: http://localhost:7070/sec04/shipping/

# 05. Splitter Pattern
sec05.car.service: http://localhost:7070/sec05/car/reserve
sec05.room.service: http://localhost:7070/sec05/room/reserve

# 06. Timeout Pattern
sec06.product.service: http://localhost:7070/sec06/product/
sec06.review.service: http://localhost:7070/sec06/review/

# 07. Retry Pattern
sec07.product.service: http://localhost:7070/sec07/product/
sec07.review.service: http://localhost:7070/sec07/review/

# 08. Circuit Breaker Pattern
sec08.product.service: http://localhost:7070/sec08/product/
sec08.review.service: http://localhost:7070/sec08/review/

# 09. Rate Limiter Pattern
sec09.product.service: http://localhost:7070/sec09/product/
sec09.review.service: http://localhost:7070/sec09/review/