### 1번 Product 조회
GET http://localhost:8080/aggregators/products/1

### 프로모션 서비스가 실패할 때 Product 조회
GET http://localhost:8080/aggregators/products/5

### 리뷰 서비스가 실패할 때 Product 조회
GET http://localhost:8080/aggregators/products/7

### 상품 서비스가 싫패할 때 Product 조회 (404)
GET http://localhost:8080/aggregators/products/51

# External Services
### Product 조회 성공
GET http://localhost:7070/sec01/product/1
accept: */*

### Product 조회 실패(404)
GET http://localhost:7070/sec01/product/51
accept: */*

### Promotion 조회 성공
GET http://localhost:7070/sec01/promotion/1
accept: */*

### Promotion 조회 실패(404)
GET http://localhost:7070/sec01/promotion/10
accept: */*

### Review 조회 성공
GET http://localhost:7070/sec01/review/1
accept: */*

### Review 조회 실패(404)
GET http://localhost:7070/sec01/review/10
accept: */*

### Review 조회 실패(500)
GET http://localhost:7070/sec01/review/7
accept: */*

