### 항공사 ATL -> LOS flight 목록 조회
GET localhost:8080/scatter-gather/flights/ATL/LOS
accept: text/event-stream

# External Services
### delta 항공사의 ATL -> LOS flight 목록 조회 (Occasional error)
GET http://localhost:7070/sec02/delta/ATL/LOS
accept: text/event-stream

### frontier 항공사의 ATL -> LOS flight 목록 조회 (Occasional error)
POST http://localhost:7070/sec02/frontier
accept: text/event-stream
Content-Type: application/json

{
  "from": "ATL",
  "to": "LOS"
}

### jetblue 항공사의 ATL -> LOS flight 목록 조회 (Occasional error)
GET http://localhost:7070/sec02/jetblue/ATL/LOS
accept: text/event-stream