### MovieId 1번 Movie 조회
GET http://localhost:8082/v1/movies/1

### MovieId 2번 Movie 조회
GET http://localhost:8082/v1/movies/2

### MovieId 3번 Movie 조회
GET http://localhost:8082/v1/movies/3

###
POST http://localhost:8080/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": 1,
  "name": "Batman Begins",
  "year": 2005,
  "cast": [
    "Christian Bale",
    "Michael Cane"
  ],
  "releasedDate": "2005-06-15"
}

###
POST http://localhost:8080/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": 2,
  "name": "The Dark Knight",
  "year": 2008,
  "cast": [
    "Christian Bale",
    "HeathLedger"
  ],
  "releasedDate": "2008-07-18"
}

###
POST http://localhost:8081/v1/reviews
Content-Type: application/json

{
  "reviewId": 1,
  "movieInfoId": 1,
  "comment": "Awesome Movie",
  "rating": 9.0
}

###
POST http://localhost:8081/v1/reviews
Content-Type: application/json

{
  "reviewId": 2,
  "movieInfoId": 1,
  "comment": "Excellent Movie",
  "rating": 8.0
}

###
POST http://localhost:8081/v1/reviews
Content-Type: application/json

{
  "reviewId": 2,
  "movieInfoId": 2,
  "comment": "Excellent Movie",
  "rating": 8.0
}

###

