### MovieInfo 1 저장
POST http://localhost:8080/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": 1,
  "name": "Batman Begins",
  "year": 2005,
  "cast": [
    "Christian Bale",
    "Michael Cane"
  ],
  "releasedDate": "2005-06-15"
}

### MovieInfo 2 저장
POST http://localhost:8080/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": 2,
  "name": "The Dark Knight",
  "year": 2008,
  "cast": [
    "Christian Bale",
    "HeathLedger"
  ],
  "releasedDate": "2008-07-18"
}

### MovieInfo 3 저장
POST http://localhost:8080/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": null,
  "name": "Dark Knight Rises",
  "year": 2012,
  "cast": [
    "Christian Bale",
    "Tom Hardy"
  ],
  "releasedDate": "2012-07-20"
}

### MovieInfo 전체 조회
GET http://localhost:8080/v1/movieinfos

### MovieInfoId 1번 MovieInfo 조회
GET http://localhost:8080/v1/movieinfos/1

### MovieInfoId 1번 MovieInfo 수정
PUT http://localhost:8080/v1/movieinfos/1
Content-Type: application/json

{
  "movieInfoId": 1,
  "name": "Batman Begins",
  "year": 2005,
  "cast": [
    "Christian Bale",
    "Michael Cane",
    "Liam Neeson"
  ],
  "releasedDate": "2005-06-15"
}

### MovieInfoId 1번 MovieInfo 삭제
DELETE http://localhost:8080/v1/movieinfos/1