POST http://localhost:8080/v1/organization/1/license
Content-Type: application/json
Accept-Language: en

{
  "id": 308,
  "licenseId": "1",
  "description": "Software product",
  "organizationId": "1",
  "productName": "Ostock",
  "licenseType": "full"
}