spring:
  application:
    name: eureka-server
  config:
    import: configserver:http://localhost:8071

---
spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://configserver:8071
