spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 10

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
