### Get Books
GET http://localhost:8080/api/books/?size=25&page=2

### Get a book by ISBN
GET http://localhost:8080/api/books/1680503545

### Get all Categories
GET http://localhost:8080/api/books/categories

###
GET http://localhost:8080/api/books/search/?q=%25scal%25

###
GET http://localhost:8080/api/books/authors/?q=brian%20s

###
GET http://localhost:8080/api/books/authors/?q=brian%20sa

###
