spring:
  redis:
    timeout: 3000 # 레디스와 커넥션을 맺은 후 명령어를 실행하고 응답받는 시간 설정
    cluster:
      nodes:
        # 하나만 연결해도 가능하지만 에러가 나면 연결이 끊긴다. 따라서 VIP, DNS, 또는 다수의 노드 연결로 해야한다.
#        - localhost:6379
        - localhost:5001
        - localhost:5002
        - localhost:5003
        - localhost:5004
        - localhost:5005
        - localhost:5006
#      max-redirects: 3 # Moved Redirection 최대 처리 횟수 설정
    password: ${REDIS_PASSWORD}
    client-name: cluster-example
    client-type: lettuce
    connect-timeout: 5000 # 레디스와 커넥션을 맺을 때 걸리는 최대 시간 설정
    lettuce:
      cluster:
        refresh: # 마스터 노드 다운 시 클러스터 노드의 Role 변경사항을 업데이트하기 위한 설정
          adaptive: true # (UNKNOWN_NODE , UNCOVERED_SLOT, PERSISTENT_RECONNECTS, ASK_REDIRECT, MOVED_REDIRECT) 등 발생했을 때 업데이트
      shutdown-timeout: 100ms # 레디스 클라이언트가 안전하게 종료하기 위해 애플리케이션이 종료될 때까지 기다리는 최대 시간
